### ISSUE TITLE
The environment configuration in ROS？

### ISSUE THREAD

**Issue by harrycomeon** [Geonhee-LEE/ur5-gripper#10]
Hello，it is a great job! Thanks for your sharing.

I have a question about the environment configuration. In an answer, you say your environment configuration is using conda python above 3 on Ubuntu 16.04 LTS.   I know the python is 2.7 in kinetic. I don't know how to install python3 in kinetic.

![image](https://user-images.githubusercontent.com/28645542/137876452-9648568a-2979-4012-8874-085d7e8f91b2.png)

But in the other answer, you say your environment configuration is melodic. 
![image](https://user-images.githubusercontent.com/28645542/137876887-692a1bf5-9611-47e1-80fb-dec4d4394b42.png)

I am looking forward to your reply!

**Comment by Geonhee-LEE** [comment]
Hi, @harrycomeon.
I used the python3 in order to use RL algorithms. I recommend you the resource: https://github.com/Geonhee-LEE/ur-reaching-reinforcement-learning/blob/e3b89772655c1ffe1badd4518ebce5ca2c0bec33/ur_openai_ros/ur_reinforcement_learning/script/ur_reinforcement_learning/ppo_gae_main.py#L12.
If you installed the rospy and dependencies, it can execute the python3 through importing rospy

**Comment by harrycomeon** [comment]
Hi, @Geonhee-LEE.

It's my honor to receive your reply. I will try to build the python3 in ROS. My ros-version is kinetic in ubuntu 16.04. Can you tell me the ros-version on your computer? Thanks a lot.

**Comment by harrycomeon** [comment]
Hi, @Geonhee-LEE.

At the same time, I find the gym is only supported by the >= 3.5. But my python is 2.7 in ros-kinetic.

**Comment by harrycomeon** [comment]
Can you tell me how to build the ros-workstation using python3? Thanks a lot.

**Comment by Geonhee-LEE** [comment]
@harrycomeon Why don't  you download the anaconda in order to use python3?

**Comment by harrycomeon** [comment]
Ok,  I will try it. Thanks.

**Comment by harrycomeon** [comment]
Hi, @Geonhee-LEE.

Yesterday, I have tried to use python3 in anaconda.  In this environment, I have built a ros-workstation and compiled it.  The instruction is 

catkin_make -DPYTHON_EXECUTABLE=/home/harry/anaconda3/bin/python3.7 -DPYTHON_INCLUDE_DIR=/home/harry/anaconda3/include/python3.7 -DPYTHON_LIBRARY=/home/harry/anaconda3/lib/libpython3.7m.so

But I have met a lot of problems in the code. I can successfully compile the code. But it can't run the instruction， which is the **roslaunch ur_training default.launch**.

I want to know the specific environment in your ubuntu. My ubuntu is the 16.04. and the ros-version is the kinetic. The python is 2.7. I build the ros-workstation by the anaconda, the python is 3.7. Can you tell me your specific environment? Thanks a lot. I am looking forward to your reply.

**Comment by harrycomeon** [comment]
> If you installed the rospy and dependencies, it can execute the python3 through importing rospy

Hello, @Geonhee-LEE.

I want to know the python-version in your ros? Because my ros is python 2.7 . It is hard to import rospy &tf in python3.

I want to know how to solve the problems?

**Comment by Geonhee-LEE** [comment]
Hi @harrycomeon .
I'm sorry to late. I don't remember exact python version.  python version used may be 3.5.
Finally, I recommend you to extract the packages step by step if fail to build. Its repository can't support stability perfectly.

**Comment by harrycomeon** [comment]
Ok, thanks a lot.

**Comment by NetpowerTechnology** [comment]
> 好的，非常感谢。

Hello, have you managed to run yet? Looking forward to your reply.
