### ISSUE TITLE
The document support

### ISSUE THREAD

**Issue by harrycomeon** [Geonhee-LEE/ur5-gripper#11]
Hi, @Geonhee-LEE.

It is a great job, I believe it can complete the tracking after a lot of training. So I want to learn the algorithm, can you give me some blog/document about the algorithm, thanks a lot.

**Comment by Geonhee-LEE** [comment]
Hi, @harrycomeon 

I referred like following:
- https://github.com/rail-berkeley/rlkit 
- https://github.com/rll/rllab

**Comment by harrycomeon** [comment]
OK, thanks a lot.
