### ISSUE TITLE
where is hopper_training.msg? Thank you

### ISSUE THREAD

**Issue by Diankuang-Wu** [Geonhee-LEE/ur5-gripper#3]
**Path**: /ur-reinforcement-learning/ur_openai_ros/ur_training/script/ur_training/default.py

**Code**:
#!/usr/bin/env python

'''
    Original Training code made by Ricardo Tellez <rtellez@theconstructsim.com>
    Moded by Miguel Angel Rodriguez <duckfrost@theconstructsim.com>
    Visit our website at www.theconstructsim.com
'''
import gym
import time
import numpy
import random
import time
from ur_training.algorithm.qlearn import *
###import our training environment
from ur_training.env.ur_default_env import URDefaultEnv
from gym import wrappers
from std_msgs.msg import Float64
###ROS packages required
import rospy
import rospkg
from **hopper_training.msg** import QLearnMatrix, QLearnElement, QLearnPoint

**Comment by Diankuang-Wu** [comment]
I annotate this line, the code run.

**Comment by Geonhee-LEE** [comment]
you can refer to https://www.theconstructsim.com/ros-projects-openai-hopper-robot-gazebo-step-step/
Actually, the code is not important but I didn't  arrange the sources.

**Comment by Diankuang-Wu** [comment]
> you can refer to https://www.theconstructsim.com/ros-projects-openai-hopper-robot-gazebo-step-step/
> Actually, the code is not importance but I didn't arrange the sources.

thank you

**Comment by SHTmlp** [comment]
thank you
