### ISSUE TITLE
cannot build the UR_kinematics

### ISSUE THREAD

**Issue by ChenyangRan** [Geonhee-LEE/ur5-gripper#4]
Hi, I'm building the project.
But when I type the command **_catkin build_**, it reports that:
``` shell

/opt/ros/kinetic/include/moveit/robot_state/robot_state.h:86:83: error: no match                                                         ing function for call to ‘moveit::core::JumpThreshold::JumpThreshold()’
   explicit JumpThreshold(double jt_revolute, double jt_prismatic) : JumpThresho                                                         ld()

``` 
Could you please help me?

Ubuntu 16.04
Ros Kinetic
![1584161026(1)](https://user-images.githubusercontent.com/29306735/76675176-b9fb4f80-65f1-11ea-93ca-684cfee52f36.jpg)

**Comment by ChenyangRan** [comment]
> 
> 
> Hi, I'm building the project.
> But when I type the command **_catkin build_**, it reports that:
> 
> ```shell
> /opt/ros/kinetic/include/moveit/robot_state/robot_state.h:86:83: error: no match                                                         ing function for call to ‘moveit::core::JumpThreshold::JumpThreshold()’
>    explicit JumpThreshold(double jt_revolute, double jt_prismatic) : JumpThresho                                                         ld()
> ```
> 
> Could you please help me?
> 
> Ubuntu 16.04
> Ros Kinetic
> ![1584161026(1)](https://user-images.githubusercontent.com/29306735/76675176-b9fb4f80-65f1-11ea-93ca-684cfee52f36.jpg)

I have solved this by changing the gcc and g++.
It seems that the gcc 4.8 cannot build ur_kinematics.

**Comment by Geonhee-LEE** [comment]
Nice one
