### ISSUE TITLE
cannot launch gazebo

### ISSUE THREAD

**Issue by ChenyangRan** [Geonhee-LEE/ur5-gripper#5]
Hi, something bad happens when I launch your code.
I really need your help.
Thank you very much.

![1584193171(1)](https://user-images.githubusercontent.com/29306735/76683104-5fd3ac00-663c-11ea-8344-e27c56e5d647.jpg)

**Comment by Geonhee-LEE** [comment]
@ChenyangRan  Did you install UR5 repository like following: https://github.com/ros-industrial/universal_robot

**Comment by ChenyangRan** [comment]
> 
> 
> @ChenyangRan Did you install UR5 repository like following: https://github.com/ros-industrial/universal_robot

Hi, I have install UR5 repository and launched well.
However,  it errors when running ur_reinforcement_main.py following tutorial.
It seems that I cannot change the controller type into 'vel'.
It's always 'pos'. 

Looking forward to your reply.

**Comment by Geonhee-LEE** [comment]
Did you install the robotiq85 package?
