### ISSUE TITLE
cannot work

### ISSUE THREAD

**Issue by ChenyangRan** [Geonhee-LEE/ur5-gripper#6]
I run the reinforcement_main.py in two branch.
First in **master branch,**
However, it errors when running ur_reinforcement_main.py following tutorial.
It seems that I **cannot change the controller type into 'vel'.**
It's **always 'pos'.**
![图片](https://user-images.githubusercontent.com/29306735/76770367-d0afcb00-67d8-11ea-9827-2ec8755e09cf.png)

Second, in **devel branch**:
The **'controller type' is 'vel**', but it **cannot also work**.
The error is :
![图片](https://user-images.githubusercontent.com/29306735/76770172-74e54200-67d8-11ea-9660-2b287d762deb.png)

Ubuntu 16.04
Ros-kinetic
Anaconda
       Python2.7
tensorflow=1.13.1

Could you please help me?
Thank you very much.

**Comment by Geonhee-LEE** [comment]
@ChenyangRan Did you install every libraries about ros and gazebo?

**Comment by ChenyangRan** [comment]
> @ChenyangRan Did you install every libraries about ros and gazebo?

I have installed moveit, openni-ros, velocity-controllers, position-controllers and some pkgs about kinectV2.
It seems ok when catkin_build your code.
Could you please tell me which pkg missing?
And must I use python2.7?
Beacuse the lower tensorflow seems cannot use my GPU.
Thanks.

**Comment by Geonhee-LEE** [comment]
@ChenyangRan  I was using conda python above 3  on Ubuntu 16.04 LTS.

Did you refer to [ReadME](https://github.com/Geonhee-LEE/ur-reinforcement-learning/tree/master/ur_openai_ros)?

**Comment by ChenyangRan** [comment]
> @ChenyangRan I was using conda python above 3 on Ubuntu 16.04 LTS.
> 
> Did you refer to [ReadME](https://github.com/Geonhee-LEE/ur-reinforcement-learning/tree/master/ur_openai_ros)?

Hi, I have checked the tutorial again, but  I cannot get the right way.
I run the ur_reinforcement_main.py in ur_reinforcement instead of ur_reach.

When I run the _** ur_reinfrocemnt.py**_, it displays content unchanged and proceeds.

When I run the _**ppo_gae_main.py**_ under ur_reinfocement, the error is:
![1585228995(1)](https://user-images.githubusercontent.com/29306735/77651859-5a655280-6fa8-11ea-851b-ac7a1e2be99c.jpg)

As for ur_reaching, the **_ppo_gae_main.py_** is 
![1585229805(1)](https://user-images.githubusercontent.com/29306735/77652950-09eef480-6faa-11ea-8f73-5e689b7e0cfd.jpg)

It seems that the env is just to reach the point instead of grasping ?

**Comment by Geonhee-LEE** [comment]
Yes, this repo goal is reaching the point
