### ISSUE TITLE
roslaunch fail with `robotiq_85_gripper not found`

### ISSUE THREAD

**Issue by letusfly85** [Geonhee-LEE/ur5-gripper#7]
Hi, where can we get `robotiq_85_gripper` modules.?

Is the following repo?

- https://github.com/StanleyInnovation/robotiq_85_gripper

I tried the repo on `/opt/ros/melodic/src` and `catkin build`, the build failed with errors.

Is there any install command list? :eyes:

**Comment by letusfly85** [comment]
And please tell me which branch works fine of this repository, is `devel` branch...?

**Comment by Geonhee-LEE** [comment]
Master branch is latest. Could u refer https://github.com/Danfoa/robotiq_2finger_grippers/tree/master/robotiq_2f_85_gripper_visualization?

**Comment by letusfly85** [comment]
Thank you!
I will try 💪

**Comment by letusfly85** [comment]
@Geonhee-LEE 

Sorry, should I replace the following lines with your refer? 👀 

from `robotiq_85_description` to `robotiq_2f_85_gripper_visualization`

https://github.com/Geonhee-LEE/ur-reinforcement-learning/search?q=robotiq_85_description

**Comment by Geonhee-LEE** [comment]
Yes, you can do because it is just for visualization for gripper.
