### ISSUE TITLE
First launch the simulator  ,have  error,and i dont solving this problem

### ISSUE THREAD

**Issue by zhanghaoboyibo** [Geonhee-LEE/ur5-gripper#8]
when i start    roslaunch ur_robotiq_gazebo gym.launch
there ia an error makes can not start the gazebo, i am so confused,would you help me,folling is the detail about error:
Invalid parameter "hw_interface" None None
when instantiating macro: ur_arm_transmission (/home/zhb/ur_ws/src/ur-reinforcement-learning/ur_description/urdf/ur.transmission.xacro)
instantiated from: ur5_robot (/home/zhb/ur_ws/src/ur-reinforcement-learning/ur_robotiq_description/urdf/ur5-vel.urdf.xacro)
in file: /home/zhb/ur_ws/src/ur-reinforcement-learning/ur_robotiq_description/urdf/ur_robotiq-vel.urdf.xacro
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/kinetic/lib/xacro/xacro --inorder '/home/zhb/ur_ws/src/ur-reinforcement-learning/ur_robotiq_description/urdf/ur_robotiq-vel.urdf.xacro'] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro --inorder '$(find ur_robotiq_description)/urdf/ur_robotiq-vel.urdf.xacro'" name="robot_description"/>
The traceback for the exception was written to the log file

waiting for your help,grateful about you!

**Comment by Geonhee-LEE** [comment]
Hi,
You need to install `hw_interface` pkg in order to use GAZEBO and associated gazebo plugin.
After installing, please tell me next error
